### ISSUE TITLE
Add an option to get defaults from a configuration file

### ISSUE THREAD

**Issue by Tieske** [amireh/lua_cliargs#20]
See [this comment](https://github.com/Olivine-Labs/busted/issues/115#issuecomment-16048767)

Can we add an option to the api that takes a list of filenames and loads options from that, which can then be overridden by the commandline provided.

example API; `function setconfigfiles(filenames)`
Provide a list of filenames as;
1. `.\my_app_name.settings`     --> project settings, overrides user settings
2. `%USERNAME%\my_app_name\user_config.settings`   --> user overrides system
3. `%ALLUSERS%\my_app_name\system_config.settings`     --> system wide config

Highest level priority would be the options on the commandline

**Comment by amireh** [comment]
Closing this since it's been implemented. :)
