### ISSUE TITLE
Update the rock in central repository

### ISSUE THREAD

**Issue by thefosk** [amireh/lua_cliargs#28]
It would be nice to update the project to its latest version on https://rocks.moonscript.org/

Right now the most recent version available is `2.1-2`, while the latest version is `2.2-0`.

**Comment by Tieske** [comment]
also; a 2.2 tag is missing in the git repo.

**Comment by amireh** [comment]
I'll do it today for 2.3 with all the changes we merged today.

**Comment by o-lim** [comment]
@amireh: I just created PR #37 which addresses some of the feedback from PR #33.

**Comment by amireh** [comment]
2.3-1 is out and available in the rock repository.

**Comment by amireh** [comment]
@o-lim: Sorry, I missed that. I'll see if I can get another release tonight.

**Comment by o-lim** [comment]
Not a problem, sorry I couldn't make the changes sooner.  I also just put in PR #38 to fix #36.
