### ISSUE TITLE
Short keys with - are getting clipped

### ISSUE THREAD

**Issue by amireh** [amireh/lua_cliargs#36]
`cli:add_opt("-Wno-unsigned", ...)` results in the key becoming `Wno-` although the label used for printing help is preserved as-is. The expected behavior is to allow `-` to appear inside the key.

**Comment by o-lim** [comment]
Sorry for all the late updates.  Just created PR #38 that should fix this.

**Comment by amireh** [comment]
Man, you're really active today. Thanks so much.

**Comment by o-lim** [comment]
It's no problem.  Any chances for a 2.3-3 release with this fix?

**Comment by amireh** [comment]
Yes, let me do it now.
