### ISSUE TITLE
feature request: named commands (myluafile.lua command)

### ISSUE THREAD

**Issue by akaRem** [amireh/lua_cliargs#48]
having something like this:

```
local cli = require "cliargs"

cli:add_option("start", "start the thing", false, function(...)
  print(...)
  os.exit(0)
end)

local args = cli:parse({ ... or '--help' })
```

I getting such error:

vagrant@vagrant:/vagrant/data/proj$ lua ./mng.lua start
migrate.lua: error: bad number of arguments: 0 argument(s) must be specified, not 1; re-run with --help for usage.

I agree with docs, but such kind of invacation is very common for cli.
It would be great if you will support it...

**Comment by amireh** [comment]
Command support would be very nice to have, but it means each command would have its own arguments and/or sub-commands and that's not a trivial change.

If you have 1 or 2 commands, you can just specify an argument (`cli:add_arg("command")`) and branch based off of its value. It does mean that the options are "global" (you can't specify different options to `start` vs `stop` for example.)

**Comment by akaRem** [comment]
@amireh 
Yes, I see workaround.
But I mean some kind of arg which has predefined set of values which are shown in --help.

**Comment by amireh** [comment]
Hey @akaRem, you might be interested to try out the basic command support in 3.0-1. Please let me know how it works out for you and what changes you might need.

**Comment by amireh** [comment]
Closing this since we have basic support for commands now.
